name: "Feature Suggestions"
description: "Suggest a new feature for CAW"
labels: "needs review"
body:
  - type: textarea
    attributes:
      label: Summary
      description: Describe the feature in 1 or 2 sentences
      placeholder: concisely describe the feature you want to see
    validations:
      required: true
